# fly.toml app configuration file generated for to-do-list-server on 2023-06-26T16:14:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "to-do-list-server"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
